### ISSUE TITLE
Converter generates extraneous `value` field in `Pulumi.yaml` config

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi-converter-terraform#178]
### What happened?

Converting from Terraform generates extra `value:` key in `Pulumi.yaml` configs. This is true for  all conversions from HCL.

### Example

When converting the following `main.tf` program to any language:
```hcl
# Configure the OpenStack Provider
provider "openstack" {
  user_name   = "admin"
  tenant_name = "admin"
  password    = "pwd"
  auth_url    = "http://myauthurl:5000/v3"
  region      = "RegionOne"
}

# Create a web server
resource "openstack_compute_instance_v2" "test-server" {
  # ...
}
```
via e.g.:
`pulumi convert --from terraform --language nodejs --generate-only`

the `Pulumi.yaml` rendered looks as follows:
```yaml
name: provider-config
runtime: nodejs
config:
  openstack:authUrl:
    value: http://myauthurl:5000/v3
  openstack:password:
    value: pwd
  openstack:region:
    value: RegionOne
  openstack:tenantName:
    value: admin
  openstack:userName:
    value: admin
```

The `value` field is unnecessary and should not be there; the lines should read like so:
```
  openstack:userName: admin
```

### Output of `pulumi about`

n/a

### Additional context

This has been generated for users using `pulumi convert` all along. It will work, but it makes the file more convoluted and confusing vs `pulumi config set`.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
